server:
  port: 9000
  context-path: /myapp
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/spring_superheroes
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect